### ISSUE TITLE
How to pass Array parameters in Postgres

### ISSUE THREAD

**Issue by mavencode01** [vert-x3/vertx-sql-common#16]
I've been stuck trying to pass in Array paramters to my postgres store procedure. Any example of how to do this ?
For example:

```
SELECT insert_info((ARRAY['(Arjay,myEmail@email.com,1234567)'
    ,'(Bjay,my2Email@email.com,2234567)'])::info[]);
```

**Comment by mavencode01** [comment]
I figured it out....when passing in array of composite types, you need to make sure you properly escape the characters in Postgres 
e.g. 

```
userList.add(String.format("\"(\\\"%s\\\",%d,\\\"%s\\\",\\\"%.2f\\\",\\\"%s\\\")\"", info.getUser(), info.getAge(), info.getDescription(), info.getApt(), info.getAddress()));
```

**Comment by Chiranjeevi545** [comment]
How to pass a string [ ] in vertx query
for example :
String[ ] userIds = {"apple","ball","cat","dog"};
how i have to make a select query using this userIds 

select * from TABLENAME where user_id IN ($1)

how to to do in vertx query

**Comment by tsegismont** [comment]
@Chiranjeevi545 change your query to `select * from TABLENAME where user_id = ANY($1)`
