### ISSUE TITLE
SQLRowStream should have a close without handler method

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-sql-common#34]
Useful avoid writing empty callbacks if you're not interested in the event.

**Comment by tsegismont** [comment]
See #35

**Comment by tsegismont** [comment]
@pmlopes can you have a look at the three PRs? Thanks!

vert-x3/vertx-sql-common#35
vert-x3/vertx-jdbc-client#81
vert-x3/vertx-mysql-postgresql-client#61

**Comment by pmlopes** [comment]
The all LGTM

**Comment by pmlopes** [comment]
All related PRs are merged.
