### ISSUE TITLE
Provide a JSON based named parameter API

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-sql-common#38]
The current API uses position based parameter typing. This maps directly to the JDBC API but has some drawbacks like lack of typing information. Using a special formatting with named parameters we can introduce a more robust API. For example:

```java
String sql = "select * from table1 where id = :id";

conn.select(sql, {id: 1});
```

In order to handle types we can do:

```java
String sql = "update table1 set col = :val#VARCHAR";

conn.update(sql, {val: 1});
```

It can even handle arrays if we would allow:

```java
String sql = "update table1 set col = :val#VARCHAR[]";

conn.update(sql, {val: 1});
```

The regex to identify params would be:

```
[^:]\:([a-zA-Z_$][0-9a-zA-Z_$]*(\[\])?)(#([a-zA-Z_$][0-9a-zA-Z_$]*(\[\])?))?
```

This would build from the basic work already done at #9 but extendable so it can be used with JDBC and the async client.

**Comment by vaIgarashi** [comment]
One year later :)

**Comment by pmlopes** [comment]
@ensirius it is all a mater of priorities and time. In the last year we've advanced on the asynchronous postgres client: https://reactiverse.io/reactive-pg-client/guide/java/ which for performance reasons does not implement these interfaces. We need to find a middle ground between the 2 projects to accommodate this.

**Comment by vietj** [comment]
actually it is not for performance reason but instead because the reactive-pg-client does not want to abstract / hide the native postgres syntax. And I think that postgres does not natively provides named parameters in its syntax.

the next generation of jdbc async driver I believe aims to behave this way as well.
