### ISSUE TITLE
Provide generated value in UpdateResult

### ISSUE THREAD

**Issue by panjiesw** [vert-x3/vertx-sql-common#4]
I think UpdatedResult should also contains, if any, generated values instead of just columnNames. Or is this by design?

In the sample of [postgresql-async-app](https://github.com/mauricio/postgresql-async-app/blob/master/app/models/MessageRepository.scala), it's shown how to get the generated value. It'd be great if vertx 3 sql modules could also support this.

**Comment by alexvetter** [comment]
:+1:

I totally agreed. In PostgreSQL it's possible to write following `UPDATE`:

``` SQL
UPDATE test SET date_column = CURRENT_TIMESTAMP, name = 'test4' where id = ? RETURNING name, date_column
```

The current implementation would only provide `name` and drop `date_column` in the `UpdateResult`. This would be the returning `JSON` for the example statement.

``` json
{
  "updated" : 1,
  "keys" : [ "test4" ]
}
```

**Comment by alexvetter** [comment]
@panjiesw

Workaround would be to do the `UPDATE` or `INSERT` statements with multiple returning columns with the `SQLConnection.query(...)` command.

**Comment by pmlopes** [comment]
resolved by https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/31
