### ISSUE TITLE
All implementation should have a common "client" interface

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-sql-common#45]
Currently all known implementations:

* jdbc
* async

share the connection interface but we should also share a client interface that returns a connection too.

The idea is that we could swap implementations.

**Comment by EmadAlblueshi** [comment]
@pmlopes do you mean that JDBCClient interface should be moved to common ?

**Comment by pmlopes** [comment]
No, we need a common ancestor and this should for now have just 2 methods:

* getConnection
* close

This way we could interchange between the jdbc and async clients as just an implementation detail.

Later we could add helper methods like:

* executeAndClose

That would do the following steps:

1. Get a connection
2. Execute the statement
3. Close the connection

This would allow a way flatter chain of callbacks.

Same for streaming.

**Comment by EmadAlblueshi** [comment]
@pmlopes the `getConnection` for async is not fluent as in jdbc WDYT ?

**Comment by EmadAlblueshi** [comment]
@pmlopes Kindly review this PR [vertx-sql-common #46](https://github.com/vert-x3/vertx-sql-common/pull/46) , [vertx-jdbc-client #99](https://github.com/vert-x3/vertx-jdbc-client/pull/99) and [vertx-mysql-postgresql-client #77](https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/77)

**Comment by chengenzhao** [comment]
There is an existing close method for Async & JDBC Clients, so closeConnection would be a better name than close method, since close method will close the whole client rather than return connection to the pool.

**Comment by pmlopes** [comment]
To close a connection you must call close on the connection object this feature is on the client.
