### ISSUE TITLE
JDBC Paged Query Example

### ISSUE THREAD

**Issue by indranilbanerjee2014** [vert-x3/vertx-sql-common#57]
Excellent examples. I am a beginner to vert.x and the examples helped me find my way. One feature I am looking for an example of is a paged query where the query returns a large number of rows and I want to read say 1000 rows at a time. Please post if you have an example handy. Appreciate all the work in posting the examples.

**Comment by tsegismont** [comment]
There is no support for pagination in the driver. You should use your
database's query language.

For example, MySQL and Postgres have LIMIT and OFFSET clauses. Recent MSSQL
and Oracle have OFFSET and FETCH.

2018-02-14 2:06 GMT+01:00 indranilbanerjee2014 <notifications@github.com>:
