### ISSUE TITLE
vertx.io website for sql common appears to have code blocks that do not resolve

### ISSUE THREAD

**Issue by anewton1998** [vert-x3/vertx-sql-common#60]
### Version

* vert.x core: 3.5.2
* vert.x sql common: 3.5.2

### Context

Viewing [vertx.io SQL common documentation](https://vertx.io/docs/vertx-sql-common/java/), all the code blocks do no render properly. It appears there is a bad link.

This appears to impact all the languages for SQL Common, not just Java.

### Do you have a reproducer?

N/A

### Steps to reproduce

1. view [website](https://vertx.io/docs/vertx-sql-common/java/)

### Extra

* I'm using Chrome on Linux and Windows
* Same result on Edge on Windows

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
will take care of it

**Comment by vietj** [comment]
fixed
