### ISSUE TITLE
Make SQLConnection implement java.io.Closeable

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-sql-common#61]
Currently `SQLConnection` implements `java.lang.AutoCloseable`. `AutoCloseable` was added so that Kotlin's [`use`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) method can manage a connection instead of more traditional `try-finally`.

But in recent versions of Kotlin, `use` no longer workers with `AutoCloseable, but with `Closeable` only.

When this is fixed, a breaking (binary) change must be logged.

**Comment by vietj** [comment]
I was under the wrong assumption that AutoCloseable extends Closeable and that's the reverse actually :-)

**Comment by vietj** [comment]
referenced here https://github.com/vert-x3/wiki/wiki/3.6.0-Breaking-Changes

**Comment by tsegismont** [comment]
Don't forget there is also an issue for updating the vertx-examples repo
3.6.0-SNAPSHOT branch.

**Comment by vietj** [comment]
can we simply revert your commit ?

**Comment by tsegismont** [comment]
Unfortunately not, it's a single commit with version upgrades and build
fixes. No worries I'll take care of the examples.

2018-06-12 17:00 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
I'm on it
