### ISSUE TITLE
SQLOperations single methods should declare a nullable asynchronous result

### ISSUE THREAD

**Issue by JEphron** [vert-x3/vertx-sql-common#62]
The (seemingly undocumented) fix for https://github.com/vert-x3/vertx-sql-common/issues/54 (aa72de8) causes querySingle to return null when the query has no result. This seems sensible at first glance, but causes a lot of headaches when working with the Rx package (especially from Kotlin, where it bypasses the null safety checks and makes for a surprising crash)

[RxJava 2 won't accept null values in streams](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls), so the behaviour of this function will probably need to change anyway.

Perhaps querySingle should return an Optional

**Comment by vietj** [comment]
This method should use an `Handler<AsyncResult<@Nullable JsonArray>>` type definition that will generate a `Maybe<JsonArray>` with RxJava2
