### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by amorozow42** [vert-x3/vertx-sql-common#65]
The package `io.vertx.ext.sql` is missing in Vertx Java docs package list.
Class list also doesn`t contain any classes related to SQL Common.
But I still can reach this package through references from Java manual.

**Comment by tsegismont** [comment]
Right, the Javadoc for `JDBCClient` and `AnsycSQLClient` is present but not the base `SQLClient` (where all useful methods are documented).

@vietj where should this be fixed, in `vertx-web-site` ?

**Comment by vietj** [comment]
this should be in vertx-stack/stack-docs
