### ISSUE TITLE
How can I configure a query timeout when using Simple SQL Operations?

### ISSUE THREAD

**Issue by gpg0** [vert-x3/vertx-sql-common#66]
### Version

* vert.x core: 3.8.0
* vert.x sql common: 3.8.0

### Context

I am using JDBCClient from vertx-jdbc-client, which extends SQLClient and implements SQLOperations, both from vertx-sql-common. According to [this](https://vertx.io/docs/vertx-sql-common/java/#_simple_sql_operations), the methods exposed by SQLOperations internally deal with getting a connection from the pool and properly returning it behind the scenes, which is nice because it saves that boilerplate code. I am actually using the rx-fied methods on JDBCClient, which come from SQLClient but delegate to the regular methods on SQLOperations.

I would like to configure a query timeout on the connection which is used internally by those methods. Is this possible? If I had a reference to an SQLConnection object, I would do `
 sqlConnection.setOptions(new SQLOptions().setQueryTimeout(timeoutInSeconds));` But the whole point of using those higher-level methods is to never have to deal with an SQLConnection instance. So how would one go about configuring it?

**Comment by gpg0** [comment]
@pmlopes @vietj Any update on this?

**Comment by vietj** [comment]
@pmlopes is that something possible ?

**Comment by activey** [comment]
Yeah, anything?

**Comment by pmlopes** [comment]
Hi, on postgres if your user is root you can call or terminate all queries for a given client pid. I don't think you can cancel a single query. The workaround is to start a timer and on timeout return an error and ignore the response.

But still the server will still be busy unless you break the connection.

For other engines it may be different though.

I guess we could have some utility to wrap a query with a timer or add it to the documentation.

The timer approach is not sql specific and can be used by other components such as web client, redis, mongo. In fact there's already a similar thing in web to timeout responses which are taking too long.
