### ISSUE TITLE
How can I disable autoGeneratedKeys when using Simple SQL Operations?

### ISSUE THREAD

**Issue by gpg0** [vert-x3/vertx-sql-common#68]
### Version

* vert.x core: 3.8.3
* vert.x sql common: 3.8.3

### Context

Hi,

I am using `io.vertx.reactivex.ext.sql.SQLConnection.rxUpdateWithParams` from vertx-sql-common and I would like to disable `autoGeneratedKeys` for those update operations. However, such a method does not provide an easy way to do it.

I know I can do it by creating an `io.vertx.reactivex.ext.sql.SQLConnection` using  `io.vertx.reactivex.ext.sql.SQLClient.rxGetConnection` and setting new `io.vertx.ext.sql.SQLOptions().setAutoGeneratedKeys(false)`. But this makes me manage the connection myself and it is causing a connection leak. This is my code:

```java
public Single <UpdateResult> rxUpdateWithParams(String sql, JsonArray arguments) {
    return getConnection().flatMap(c - > c.rxUpdateWithParams(sql, arguments).doAfterTerminate(() - > returnToPool(c)));
}

protected Single <SQLConnection> getConnection() {
    return client.rxGetConnection().map(c - > {
        c.setOptions(new SQLOptions()
            .setAutoGeneratedKeys(false));
        return c;
    });
}
protected void returnToPool(SQLConnection connection) {
    connection.close();
}
```

Is there any other way of disabling autoGeneratedKeys? Perhaps a config file that vertx will honor? Or a config I can set when creating my JDBC client?

**Comment by aesteve** [comment]
In which cases is it causing connection leaks?
Have you tried `doFinally` instead?
I've used such methods in the past (Kotlin):


```kotlin
    fun getConnection() : Single<SqlConnection> {
        var connection: SqlConnection? = null
        return pool
            .rxGetConnection()
            .subscribeOn(RxHelper.scheduler(vertx))
            .map {
                connection = it
                it
            }
            .doFinally {
                connection?.close()
            }
    }

```
And did not experience leaks as far as I'm aware of.

**Comment by gpg0** [comment]
Thanks @aesteve for confirming that you’re not experiencing a connection leak when using `doFinally`. I’ll give that a try over doAfterTerminate. For anyone reading this, the not very documented `SQLClientHelper.usingConnectionSingle` already handles this.

**Comment by gpg0** [comment]
Regardless of that, my initial question persists. Is there a way to configure JDBC to disable autoGeneratedKeys which allows such a configuration to be in effect when using `io.vertx.reactivex.ext.sql.SQLConnection.rxUpdateWithParams`?

**Comment by tsegismont** [comment]
@pasku indeed, in https://vertx.io/docs/vertx-sql-common/java/#_rxjava_2_api only the transaction management helpers are documented. Would you mind to contribute an update about `usingConnectionXXX` methods? I can help you in this process?

Setting connection options is a synchronous operation, you can do it in `doOnSuccess`:

```java
protected Single <SQLConnection> getConnection() {
    return client.rxGetConnection()
      .doOnSuccess(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(false)));
}
```

Or with `usingConnectionSingle`:

```java
SQLClientHelper.(client, c -> {
  c.setOptions(new SQLOptions().setAutoGeneratedKeys(false));

  // your code here

  return single;
});
```

Back to your original question, returning the generated keys is the default, and there is no other way to change this than calling `setOptions` on the `SQLConnection`.
