### ISSUE TITLE
Data Type BIGINT seems to be not supported

### ISSUE THREAD

**Issue by ericdoerheit** [vert-x3/vertx-sql-common#8]
I try to select attributes from a table which are of the type BIGINT. I get the following error message:
`Illegal type in JsonObject: class java.math.BigDecimal`

A workaround would be to change the data-type but in my case this is not possible. What could be a way to solve this problem?

Thanks in advance

**Comment by pmlopes** [comment]
BIGINT should not be mapped to BigDecimal, BigDecimal as it names states is a decimal number, you should map BIGINT to BigInteger and that is supported by our JSON. Currently BigDecimal is not supported by our currentl JSON implementation

**Comment by ericdoerheit** [comment]
You're right. BIGINT is properly mapped to BigDecimal. The problem is the Mapping from DECIMAL to BigDecimal. Fortunately we could change the datatype in our database to DOUBLE and now it is working fine.
Thank you
